name: CI

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Dependencies
        run: ./setup.sh
      - name: Generate Sources and Build
        run: ./run.sh
      - name: Lint Python
        run: |
          python -m py_compile $(git ls-files '*.py')
      - name: Run Tests
        run: pytest -q
